"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Zulu = exports.Russian = exports.Roman = exports.Mongol = exports.Indian = exports.Greek = exports.German = exports.French = exports.English = exports.Egyptian = exports.Chinese = exports.Babylonian = exports.Aztec = exports.American = void 0;
var American_1 = require("@civ-clone/base-civilization-american/American");
Object.defineProperty(exports, "American", { enumerable: true, get: function () { return American_1.American; } });
var Aztec_1 = require("@civ-clone/base-civilization-aztec/Aztec");
Object.defineProperty(exports, "Aztec", { enumerable: true, get: function () { return Aztec_1.Aztec; } });
var Babylonian_1 = require("@civ-clone/base-civilization-babylonian/Babylonian");
Object.defineProperty(exports, "Babylonian", { enumerable: true, get: function () { return Babylonian_1.Babylonian; } });
var Chinese_1 = require("@civ-clone/base-civilization-chinese/Chinese");
Object.defineProperty(exports, "Chinese", { enumerable: true, get: function () { return Chinese_1.Chinese; } });
var Egyptian_1 = require("@civ-clone/base-civilization-egyptian/Egyptian");
Object.defineProperty(exports, "Egyptian", { enumerable: true, get: function () { return Egyptian_1.Egyptian; } });
var English_1 = require("@civ-clone/base-civilization-english/English");
Object.defineProperty(exports, "English", { enumerable: true, get: function () { return English_1.English; } });
var French_1 = require("@civ-clone/base-civilization-french/French");
Object.defineProperty(exports, "French", { enumerable: true, get: function () { return French_1.French; } });
var German_1 = require("@civ-clone/base-civilization-german/German");
Object.defineProperty(exports, "German", { enumerable: true, get: function () { return German_1.German; } });
var Greek_1 = require("@civ-clone/base-civilization-greek/Greek");
Object.defineProperty(exports, "Greek", { enumerable: true, get: function () { return Greek_1.Greek; } });
var Indian_1 = require("@civ-clone/base-civilization-indian/Indian");
Object.defineProperty(exports, "Indian", { enumerable: true, get: function () { return Indian_1.Indian; } });
var Mongol_1 = require("@civ-clone/base-civilization-mongol/Mongol");
Object.defineProperty(exports, "Mongol", { enumerable: true, get: function () { return Mongol_1.Mongol; } });
var Roman_1 = require("@civ-clone/base-civilization-roman/Roman");
Object.defineProperty(exports, "Roman", { enumerable: true, get: function () { return Roman_1.Roman; } });
var Russian_1 = require("@civ-clone/base-civilization-russian/Russian");
Object.defineProperty(exports, "Russian", { enumerable: true, get: function () { return Russian_1.Russian; } });
var Zulu_1 = require("@civ-clone/base-civilization-zulu/Zulu");
Object.defineProperty(exports, "Zulu", { enumerable: true, get: function () { return Zulu_1.Zulu; } });
//# sourceMappingURL=Civilizations.js.map