"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Shaka = exports.JosephStalin = exports.JuliusCaesar = exports.GenghisKhan = exports.MahatmaGandhi = exports.AlexanderTheGreat = exports.FrederickTheGreat = exports.NapoleonI = exports.ElizabethI = exports.RamessesII = exports.MaoZedong = exports.Hammurabi = exports.MoctezumaII = exports.AbrahamLincoln = void 0;
var Leaders_1 = require("@civ-clone/base-civilization-american/Leaders");
Object.defineProperty(exports, "AbrahamLincoln", { enumerable: true, get: function () { return Leaders_1.AbrahamLincoln; } });
var Leaders_2 = require("@civ-clone/base-civilization-aztec/Leaders");
Object.defineProperty(exports, "MoctezumaII", { enumerable: true, get: function () { return Leaders_2.MoctezumaII; } });
var Leaders_3 = require("@civ-clone/base-civilization-babylonian/Leaders");
Object.defineProperty(exports, "Hammurabi", { enumerable: true, get: function () { return Leaders_3.Hammurabi; } });
var Leaders_4 = require("@civ-clone/base-civilization-chinese/Leaders");
Object.defineProperty(exports, "MaoZedong", { enumerable: true, get: function () { return Leaders_4.MaoZedong; } });
var Leaders_5 = require("@civ-clone/base-civilization-egyptian/Leaders");
Object.defineProperty(exports, "RamessesII", { enumerable: true, get: function () { return Leaders_5.RamessesII; } });
var Leaders_6 = require("@civ-clone/base-civilization-english/Leaders");
Object.defineProperty(exports, "ElizabethI", { enumerable: true, get: function () { return Leaders_6.ElizabethI; } });
var Leaders_7 = require("@civ-clone/base-civilization-french/Leaders");
Object.defineProperty(exports, "NapoleonI", { enumerable: true, get: function () { return Leaders_7.NapoleonI; } });
var Leaders_8 = require("@civ-clone/base-civilization-german/Leaders");
Object.defineProperty(exports, "FrederickTheGreat", { enumerable: true, get: function () { return Leaders_8.FrederickTheGreat; } });
var Leaders_9 = require("@civ-clone/base-civilization-greek/Leaders");
Object.defineProperty(exports, "AlexanderTheGreat", { enumerable: true, get: function () { return Leaders_9.AlexanderTheGreat; } });
var Leaders_10 = require("@civ-clone/base-civilization-indian/Leaders");
Object.defineProperty(exports, "MahatmaGandhi", { enumerable: true, get: function () { return Leaders_10.MahatmaGandhi; } });
var Leaders_11 = require("@civ-clone/base-civilization-mongol/Leaders");
Object.defineProperty(exports, "GenghisKhan", { enumerable: true, get: function () { return Leaders_11.GenghisKhan; } });
var Leaders_12 = require("@civ-clone/base-civilization-roman/Leaders");
Object.defineProperty(exports, "JuliusCaesar", { enumerable: true, get: function () { return Leaders_12.JuliusCaesar; } });
var Leaders_13 = require("@civ-clone/base-civilization-russian/Leaders");
Object.defineProperty(exports, "JosephStalin", { enumerable: true, get: function () { return Leaders_13.JosephStalin; } });
var Leaders_14 = require("@civ-clone/base-civilization-zulu/Leaders");
Object.defineProperty(exports, "Shaka", { enumerable: true, get: function () { return Leaders_14.Shaka; } });
//# sourceMappingURL=Leaders.js.map