export {
  AbrahamLincoln,
  MoctezumaII,
  Hammurabi,
  MaoZedong,
  RamessesII,
  ElizabethI,
  NapoleonI,
  FrederickTheGreat,
  AlexanderTheGreat,
  MahatmaGandhi,
  GenghisKhan,
  JuliusCaesar,
  JosephStalin,
  Shaka,
} from '@civ-clone/library-civilization/Leaders';
